#!/bin/sh

#!mail-farm

SESH="mail-farm"

tmux has-session -t $SESH 2> /dev/null
if [ $? != 0 ]; then 

  tmux new-session -d -s $SESH -n "editor"
  tmux send-keys -t $SESH:editor "cd /home/ghostgamer/Codes/mail-farm/" C-m
  tmux send-keys -t $SESH:editor "nvim" C-m
  tmux send-keys -t $SESH:editor ":NvimTreeToggle" C-m
  
  tmux new-window -t $SESH -n "gemini"
  tmux send-keys -t $SESH:gemini "cd /home/ghostgamer/Codes/mail-farm/" C-m
  tmux send-keys -t $SESH:gemini "gemini" C-m
  
  tmux select-window -t $SESH:editor

fi

tmux attach-session -t $SESH
