#!/bin/sh

#!notes

SESH="notes"

tmux has-session -t $SESH 2> /dev/null
if [ $? != 0 ]; then 

  tmux new-session -d -s $SESH -n "notes"
  tmux send-keys -t $SESH:notes "cd /home/ghostgamer/Arambh/Vault/" C-m
  tmux send-keys -t $SESH:notes "yazi" C-m

  tmux select-window -t $SESH:notes
fi

tmux attach-session -t $SESH
