#!/bin/bash

# tor starter


sudo tor --SocksPort 9052 --ControlPort 9053 --DataDirectory /tmp/tor2 &
sudo tor --SocksPort 9054 --ControlPort 9055 --DataDirectory /tmp/tor3 &
sudo tor --SocksPort 9056 --ControlPort 9057 --DataDirectory /tmp/tor4 &
sudo tor --SocksPort 9058 --ControlPort 9059 --DataDirectory /tmp/tor5 &
sudo tor --SocksPort 9060 --ControlPort 9061 --DataDirectory /tmp/tor6 &
sudo tor --SocksPort 9062 --ControlPort 9063 --DataDirectory /tmp/tor7 &
sudo tor --SocksPort 9064 --ControlPort 9065 --DataDirectory /tmp/tor8 &
