#!/bin/sh

# background apps
configs &
rust-book &

# check if tmux session "0" exists
if tmux has-session -t 0 2>/dev/null; then
    tmux attach-session -t 0   # attach to session 0
else
    tmux new-session -s 0      # create a new session named 0
fi
